from pathlib import Path
import csv
root=Path('Assets/Castle/Content/CSV')
headers={'Room':'id,name,floor,start,end,need','Event':'id,name,room,trigger,target,start,end,need,plot,time,reward,use,goal,plan_b,action,record','Plot':'id,group,order,speaker,text,at,anchor,link_entry','Record':'id,name,device,start,duration,plot,need','Entry':'id,name,type,text,icon,owner,record,source','Puzzle':'id,name,type,need,target,map,slots,candidates,answer,reference,success,feedback,fail_text'}
data={k:[] for k in headers}
def add(table,**kw):data[table].append(kw)
def plot(group,lines,timed=False):
 for i,line in enumerate(lines):
  text,speaker,anchor,link=line if isinstance(line,tuple) else (line,'旁白',False,'')
  add('Plot',id=f'L_{group}_{i+1}',group=f'P_{group}',order=i+1,speaker=speaker,text=text,at=i*3 if timed else '',anchor=str(anchor).lower(),link_entry=link)
def event(id,name,group='',room='',trigger='flow',need='',reward='',time=0,goal=None,**kw):add('Event',id='E_'+id,name=name,room=room,trigger=trigger,need=need,plot='P_'+group if group else '',time=time,reward=reward,goal=goal or 'G_'+id,action='none',**kw)
def entry(id,name,type,text,**kw):add('Entry',id=id,name=name,type=type,text=text,**kw)
for id,name,floor,start,end,need in [('HALL','大厅',1,'00:00','24:00',''),('HOME','女主房间',2,'00:00','24:00','G_ARRIVE'),('STUDY','书房',2,'08:00','22:00','G_TUTORIAL'),('CONTROL','中控室',1,'08:00','23:00','G_TUTORIAL;I_MAP')]:add('Room',id='R_'+id,name=name,floor=floor,start=start,end=end,need=need)
plot('INVITE',['一封邀请函将你带到古堡。这是一宗用于联调的示例案件：访客为何两次出现在大厅？','请结合录音、维护记录和访客证词完成调查。正式案件剧情待策划替换。'])
plot('ARRIVE',[('请收下地图。回到二楼房间，先听剧情磁带，再到书房调查。','管家',False,'I_MAP'),'接待用时十五分钟；中央设备保留了今晚的测试录音。'])
plot('TUTORIAL',['在女主房间使用放音机，选择剧情磁带。请完整播放指定录音后回来点击继续。'])
plot('TAPE',['这里记录的是访客的留言。','我离开大厅去了二楼书房，随后又回到大厅。','书房维护簿记录着参考设备的检修结果。'],True)
plot('LIVE',[('我先在大厅登记，然后上楼去书房，最后返回大厅。','访客',False,''),('第二次回到大厅时，钟敲过一次；随后才听见金属箱落地。','访客',False,''),'这段证词已由随身录音笔记录。'],True)
plot('MAINT',[('维护记录证明频道A与标准时钟一致。','记录',False,'C_PROOF'),'频道B的窗旁录音含翻页声，与书房环境对应。'])
plot('MISS',['访客留下了大厅登记信息。当天错过也可通过备用留言领取。'])
plot('BACK',['访客已经离开，登记台留下相同内容的备忘录。'])
plot('A',[('整点钟响之后，金属箱突然坠地。','声响',True,''),'参考时钟记录了这次声响。'],True)
plot('B',[('整点钟响之后，远处传来同一次金属撞击。','声响',True,''),('近处有人合上书本；窗边风声持续。','环境',False,'')],True)
plot('C',[('稍后，工作人员再次试敲空箱——这是第二次声响。','声响',True,''),'该声响并非访客听到的第一次撞击。'],True)
plot('REL',['先登记，才有离开大厅前往书房的行程。','书房停留结束后，访客返回大厅听见第一次撞击。'])
plot('END',['分散的录音逐渐重合。','校正后的时钟表明，这些片段可以放在同一条时间线上。','访客先登记，随后查阅书房，再返回大厅；第二次试敲声不属于这段行程。'],True)
for id,text in [('ANCHOR','已验证同一次声响，干扰声响已排除。'),('LOCATION','设备位置已确认，今后显示已知房间。'),('CALIBRATE','设备B慢了三分钟，报告时间加三分钟得到校正时间。'),('PATH','已验证访客由大厅到书房再返回大厅。'),('TIMELINE','事件先后关系已确定，可选择最终推论。')]:plot('REWARD_'+id,[text])
event('INVITE','邀请函','INVITE')
event('ARRIVE','管家接待','ARRIVE',need='G_INVITE',reward='I_TAPE;I_BLANK',time=15)
event('TUTORIAL','房间磁带引导','TUTORIAL',need='G_ARRIVE;I_TAPE')
event('LIVE','访客现场证词','LIVE','R_STUDY','interact','G_TUTORIAL',reward='C_PATH',time=5,target='HS_VISITOR',start='08:00',end='22:00',record='REC_PERSONAL')
event('MAINT','检查维护簿','MAINT','R_STUDY','interact','G_TUTORIAL',reward='C_PROOF;C_ROOM',time=5,target='HS_BOOK',start='08:00',end='22:00')
event('MISS','限时登记信息','MISS','R_HALL','interact','G_TUTORIAL',reward='C_REGISTER',time=0,target='HS_DESK',start='18:45',end='19:10',plan_b='E_BACK')
event('BACK','备用登记留言','BACK','R_HALL','interact','G_TUTORIAL',reward='C_REGISTER',time=0,goal='G_MISS',target='HS_DESK',start='00:00',end='24:00')
for id,reward in [('ANCHOR','V_RETURN'),('LOCATION','V_STUDY'),('CALIBRATE','C_TIME'),('PATH','V_REGISTER'),('TIMELINE','')]:event('REWARD_'+id,id+'验证奖励','REWARD_'+id,trigger='reward',reward=reward)
add('Event',id='E_END',name='真相重构',trigger='reward',plot='P_END',time=0,goal='G_END',action='ending')
entry('I_MAP','地图','item','古堡两层地图。',source='L_ARRIVE_1')
entry('I_TAPE','剧情磁带','tape','访客留下的录音。',record='REC_TAPE',source='E_ARRIVE')
entry('I_BLANK','空白磁带','tape','在中控室刻录完整文件。',source='E_ARRIVE')
entry('C_PROOF','维护记录','clue','频道A已对准标准时钟，原始时间可信。',source='L_MAINT_1')
entry('C_ROOM','环境记录','clue','窗旁风声、翻书声对应书房设备。',source='L_MAINT_2;L_B_2')
entry('C_PATH','访客行程','info','访客说先在大厅登记，再去书房，最后回到大厅。',owner='CHAR_VISITOR',source='L_LIVE_1')
entry('C_REGISTER','登记信息','info','访客在前往书房之前已完成登记。',owner='CHAR_VISITOR',source='E_MISS;E_BACK')
entry('C_TIME','已校正时钟','clue','频道B比参考设备慢180秒，已统一修正其文件时间。',source='Q_CALIBRATE')
for id,name,text,source in [('REGISTER','大厅登记','访客首先在大厅登记。','Q_PATH'),('STUDY','书房停留','访客在书房查阅资料。','Q_LOCATION'),('RETURN','返回大厅','访客返回大厅，听到第一次金属箱撞击。','Q_ANCHOR')]:entry('V_'+id,name,'event',text,owner='CHAR_VISITOR',source=source)
entry('K_TRUE','登记 → 书房 → 返回大厅','conclusion','第一次撞击对应返回大厅后的时刻；再次试敲是干扰。')
entry('K_FALSE','两次撞击属于同一时刻','conclusion','假设试敲与第一次撞击完全相同。')
for id,device,start,group,need in [('A','D_A','2026-10-07 18:50:00','A','G_TUTORIAL'),('B','D_B','2026-10-07 18:47:00','B','G_TUTORIAL'),('C','D_C','2026-10-07 18:52:00','C','G_TUTORIAL'),('PERSONAL','D_PERSONAL','','LIVE',''),('TAPE','','2026-10-07 18:30:00','TAPE','TAPE_ONLY')]:add('Record',id='REC_'+id,name={'PERSONAL':'现场文件01','TAPE':'留言文件'}.get(id,'档案'+id),device=device,start=start,duration=10,plot='P_'+group,need=need)
def puzzle(id,name,type,need,candidates,answer='',**kw):add('Puzzle',id='Q_'+id,name=name,type=type,need=need,candidates=candidates,answer=answer,success='E_REWARD_'+id,fail_text='证据尚不支持这组判断。草稿已保留，请重新比对。',**kw)
puzzle('ANCHOR','同一次声响','anchor','G_TUTORIAL','L_A_1;L_B_1;L_C_1','L_A_1;L_B_1')
puzzle('LOCATION','频道B位置','location','C_ROOM','R_HALL;R_STUDY;R_HOME',target='D_B',map='MAP_CASTLE')
puzzle('CALIBRATE','频道B校时','calibrate','Q_ANCHOR','L_A_1;L_B_1;L_C_1',target='D_B',reference='D_A;D_C')
puzzle('PATH','访客路径','person_path','C_PATH;C_REGISTER','N_HALL;N_STUDY;N_HOME','A=N_HALL;B=N_STUDY;C=N_HALL',target='CHAR_VISITOR',map='MAP_CASTLE',slots='A;B;C')
puzzle('TIMELINE','事件时间线','timeline','Q_ANCHOR;Q_LOCATION;Q_CALIBRATE;Q_PATH','V_REGISTER;V_STUDY;V_RETURN','S1=V_REGISTER;S2=V_STUDY;S3=V_RETURN',slots='S1;S2;S3',feedback='P_REL')
add('Puzzle',id='Q_CONCLUSION',name='最终推论',type='conclusion',need='Q_TIMELINE',target='Q_TIMELINE',candidates='K_TRUE;K_FALSE',answer='K_TRUE',success='E_END',fail_text='请回看时间线；另一声撞击发生得更晚。')
for table,rows in data.items():
 with (root/(table+'.csv')).open('w',encoding='utf-8',newline='') as f:
  writer=csv.DictWriter(f,fieldnames=headers[table].split(','),lineterminator='\n');writer.writeheader();writer.writerows(rows)
